### ISSUE TITLE
查詢股票代碼我遇到 當有光這個字 會查不到 

### ISSUE THREAD

**Issue by stereo720712** [Asoul/tsrtc#2]
如題 很怪,請問您有碰到嗎
http://mis.twse.com.tw/stock/api/getStockNames.jsp?n=%E5%85%89&_=1450430947766
像是打n=日月光 有事 查不到
n=日月就成功
其他也一樣
想請問是否有好的方法解掉

**Comment by Asoul** [comment]
我也不知道這樣是他那邊的查詢問題或是什麼的，不過想到的方法是：
http://mis.twse.com.tw/stock/api/getStockNames.jsp?n=d&_=1450430947766

他這個網址好像是列出所有的清單，所以他那邊查詢不到的話就在自己做搜尋吧

**Comment by stereo720712** [comment]
沒想到可以直接撈所有清單 謝謝！
