### ISSUE TITLE
Failed to establish a new connection: [Errno 110] Connection timed out',

### ISSUE THREAD

**Issue by snowuyl** [Asoul/tsrtc#3]
Dear Asoul,

```
    I changed stocknumber.csv to contain 2330 only. And then I type the following command to get stock information.
```

python crawl.py

But the following error occurred.  
HTTPConnectionPool(host='1.1.1.3', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f14c4029e10>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Do you have any suggestion to fix this issue?

Thanks in advance!

snowuyl

**Comment by Asoul** [comment]
Hi snowuyl,

Recently I don't have time to check this, if you have some amendment, you can send a PR.

**Comment by Asoul** [comment]
Hi @snowuyl,
Yesterday I changed the stocknumber.csv, and things work well. I think that was some wrong stock id, so the server failed.
